version: '3.5'

volumes:
  zookeeper-data-volume:
  zookeeper-logs-volume:
  kafka-data-volume:
  kafka-logs-volume:

networks:
  tools-network:

services:

  zookeeper:
    image: zookeeper:latest
    volumes:
      - zookeeper-data-volume:/data
      - zookeeper-logs-volume:/datalog
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - tools-network

  # https://github.com/ches/docker-kafka
  kafka:
    image: ches/kafka:latest
    volumes:
      - kafka-data-volume:/data
      - kafka-logs-volume:/logs
    ports:
      - 9092:9092
    networks:
      - tools-network
    environment:
      ZOOKEEPER_IP: zookeeper
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"