version: '3.5'

volumes:
  registry-images-volume:

services:
  registry:
    image: registry:latest
    restart: always
    volumes:
      - registry-images-volume:/var/lib/registry
    ports:
      - 5000:5000