---

# get_url not work
- name: Install Docker Compose
  shell: curl -L "{{ docker.compose.download_url }}" -o /usr/local/bin/docker-compose
  become: yes

- file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  become: yes

- name: Check Installed Docker Version
  shell: docker version
  register: docker_installed_version
  become: yes

- debug:
    var: docker_installed_version.stdout_lines