version: '3.5'

services:

  # Deploy Config https://docs.docker.com/compose/compose-file/#mode
  kafka-java:
    image: localhost:5000/devops/kafka-java:latest
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager