---

- name: Install Linux Extra for AUFS storage driver
  apt:
    name:
      - linux-image-extra-virtual
    update_cache: yes
  become: yes

- name: Install Tools for Docker Setup (https, curl, ...)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
  become: yes

- name: Add Docker GPG Key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable
  become: yes

- name: Install Docker Community Edition
  apt:
    name:
      - docker-ce
    update_cache: yes
  become: yes