---

# Takes lot of time and that's optional
# - name: Install Linux Extra for AUFS storage driver
#   apt:
#     name:
#       - linux-image-extra-virtual
#     update_cache: yes
#   become: yes

- name: Install Tools for Docker Setup (https, curl, ...)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
  become: yes

- name: Add Docker GPG Key
  shell: curl -fsSL "{{ apt.docker.gpg_key }}" | apt-key add -
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] "{{ apt.docker.base_url }}" trusty stable
  become: yes

- name: Install Docker Community Edition
  apt:
    name:
      - docker-ce
    update_cache: yes
  become: yes