---

- name: Initialize Docker Swarm on Manager
  hosts: manager
  roles:
    - manager

- name: Add worker to Swarm Node
  hosts: worker
  roles:
    - worker

- name: Execute Swarm Checks
  hosts: manager
  roles:
    - check